[character]
error_symbol = ""
symbol = ""
use_symbol_for_status = true
vicmd_symbol = ""

[git_branch]
symbol = " "

[kubernetes]
symbol = "ﴱ "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "
